version: "3.9"

services:
  dashboard:
    build: ./backend/dashboard
    image: nirmalazurecr.azurecr.io/dashboard
    container_name: cn_dashboard
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: node dist/server.js
    depends_on:
      - logs
      - exercise
      # - redis-database

  logs:
    build: ./backend/logs
    image: nirmalazurecr.azurecr.io/logs
    env_file:
      - .env
    container_name: ch_journal_logs
    ports:
      - "4000:3000"
    command: node dist/server.js

  users:
    build: ./backend/users
    image: nirmalazurecr.azurecr.io/users
    env_file:
      - .env
    container_name: cn_users
    ports:
      - "5000:3000"
    command: node dist/server.js

  notifications:
    build: ./backend/notifications
    image: nirmalazurecr.azurecr.io/notifications
    env_file:
      - .env
    container_name: cn_notifications
    ports:
      - "6000:3000"
    command: node dist/server.js
    depends_on:
      - logs

  exercise:
    build: ./backend/exercise
    image: nirmalazurecr.azurecr.io/exercise
    env_file:
      - .env
    container_name: cn_exercise
    ports:
      - "7000:3000"
    command: node dist/server.js
#   redis-database:
#     image: redis/redis-stack:latest
#     image: cloudnativekubernetesservices.azurecr.io/redis-stack
#     container_name: redis-stack
#     ports:
#       - "6379:6379"
#       - "8001:8001"
#     restart: always
#     volumes:
#       - redisData:/data

# volumes:
#   redisData:
