version: '3.9'

services:
  nginx:
    build: ./nginx
    container_name: cn_nginx
    depends_on:
      - dashboard
      - logs
    ports:
      - "80:80"

  dashboard:
    build: ./backend/dashboard
    container_name: cn_dashboard
    ports:
      - "3000:3000"
    command: node dist/server.js

  logs:
    build: ./backend/logs
    container_name: ch_journal_logs
    ports: 
      - "4000:3000"
    command: node dist/server.js
  users:
    build: ./backend/users
    env_file:
      - .env
    container_name: cn_users
    ports:
      - "5000:3000"
    command: node dist/server.js