version: "3.9"

services:
  nginx:
    build: ./nginx
    container_name: cn_nginx
    depends_on:
      - dashboard
      - logs
      - users
    ports:
      - "80:80"

  dashboard:
    build: ./backend/dashboard
    container_name: cn_dashboard
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: node dist/server.js
    depends_on:
      - logs
      - exercise

  logs:
    build: ./backend/logs
    env_file:
      - .env
    container_name: ch_journal_logs
    ports:
      - "4000:3000"
    command: node dist/server.js

  users:
    build: ./backend/users
    env_file:
      - .env
    container_name: cn_users
    ports:
      - "5000:3000"
    command: node dist/server.js

  notifications:
    build: ./backend/notifications
    env_file:
      - .env
    container_name: cn_notifications
    ports:
      - "6000:3000"
    command: node dist/server.js
    depends_on:
      - logs

  exercise:
    build: ./backend/exercise
    env_file:
      - .env
    container_name: cn_exercise
    ports:
      - "7000:3000"
    command: node dist/server.js
