version: '3.9'

services:
  nginx:
    build: ./nginx
    container_name: cn_nginx
    depends_on:
      - dashboard
      - habit
    ports:
      - "80:80"

  dashboard:
    build: ./backend/dashboard
    container_name: cn_dashboard
    ports:
      - "3000:3000"
    command: node dist/server.js

  habit:
    build: ./backend/habit
    container_name: cn_habit
    ports: 
      - "4000:3000"
    command: node dist/server.js
