apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-deployment
  labels:
    app: exercise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
        - name: exercise
          image: nirmalAzureContainerRegistry.azurecr.io/exercise:v1
          ports:
            - containerPort: 3000
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: cloudnative-config

---
apiVersion: v1
kind: Service
metadata:
  name: exercise-service
spec:
  selector:
    app: exercise
  ports:
    - name: express
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082
