apiVersion: v1
kind: ConfigMap
metadata:
  name: exercise-config
data:
  MONGO_DB_NAME: habit_tracker
  MONGO_DB_USER: bhdnirmal99
  MONGO_DB_PASSWORD:
  MONGO_DB_HOST:
  JWT_ACCESS_TOKEN_SECRET:
  JWT_REFRESH_TOKEN_SECRET:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-deployment
  labels:
    app: exercise
spec:
  replicas: 5
  selector:
    matchLabels:
      app: exercise
  template:
    metadata:
      labels:
        app: exercise
    spec:
      containers:
        - name: exercise
          image: nirmalazurecr.azurecr.io/exercise
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "640Mi"
          envFrom:
            - configMapRef:
                name: exercise-config
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: exercise-service
spec:
  selector:
    app: exercise
  ports:
    - name: express
      protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: exercise-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: exercise-deployment
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
