apiVersion: v1
kind: ConfigMap
metadata:
  name: logs-config
data:
  MONGO_DB_NAME: habit_tracker
  MONGO_DB_USER: bhdnirmal99
  MONGO_DB_PASSWORD:
  MONGO_DB_HOST:
  JWT_ACCESS_TOKEN_SECRET:
  JWT_REFRESH_TOKEN_SECRET:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-deployment
  labels:
    app: logs
spec:
  replicas: 5
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: logs
          image: nirmalazurecr.azurecr.io/logs
          ports:
            - containerPort: 3000
            - containerPort: 8082
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "640Mi"

          envFrom:
            - configMapRef:
                name: logs-config
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: logs-service
spec:
  selector:
    app: logs
  ports:
    - name: express
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logs-deployment
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
