apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  MONGO_DB_NAME: habit_tracker
  MONGO_DB_USER: nirmaladmin
  MONGO_DB_PASSWORD: TempPass123!
  MONGO_DB_HOST: mongodb+srv://nirmaladmin:TempPass123!@mongodb-monolithic.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
  JWT_ACCESS_TOKEN_SECRET: e5f3f839b5c8678377ca97cd373f51f28d0c69e5f60726c4d79b7626bc401e6e6209768f83a7c3634e64329966eb6774596c91250dce24af68fe4d5f5912aecc
  JWT_REFRESH_TOKEN_SECRET: 7af4989628b9c23bdeb29247ddf74df3ffbb15f39318ebe298e87dd55e2aaa79cbc6f8e1635924914702276d26ba7833e63f8e72b105e7cf3c7940fd6eeac470
  LOG_SERVER_ID: logs-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: nirmalAzureContainerRegistry.azurecr.io/notifications:v2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: notifications-config

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
