apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  MONGO_DB_NAME: habit_tracker
  MONGO_DB_USER: bhdnirmal99
  MONGO_DB_PASSWORD: zfNQDY7JYLgQhjp9
  MONGO_DB_HOST: mongodb+srv://bhdnirmal99:zfNQDY7JYLgQhjp9@serverless-notification.0acfha9.mongodb.net/?retryWrites=true&w=majority&appName=serverless-notification-db
  JWT_ACCESS_TOKEN_SECRET: e5f3f839b5c8678377ca97cd373f51f28d0c69e5f60726c4d79b7626bc401e6e6209768f83a7c3634e64329966eb6774596c91250dce24af68fe4d5f5912aecc
  JWT_REFRESH_TOKEN_SECRET: 7af4989628b9c23bdeb29247ddf74df3ffbb15f39318ebe298e87dd55e2aaa79cbc6f8e1635924914702276d26ba7833e63f8e72b105e7cf3c7940fd6eeac470
  LOG_SERVER_ID: logs-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-deployment
  labels:
    app: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: nirmalazurecr.azurecr.io/notifications
          ports:
            - containerPort: 3000
            - containerPort: 8082
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "170m"
              memory: "640Mi"
          envFrom:
            - configMapRef:
                name: notifications-config
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: notifications-service
spec:
  selector:
    app: notifications
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
    - name: grpc
      protocol: TCP
      port: 8082
      targetPort: 8082

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: notifications-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notifications-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
