apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
data:
  SQL_DB_NAME: cn_habit_tracker
  SQL_DB_USER: nirmaladmin
  SQL_DB_PASSWORD:
  SQL_DB_HOST:
  SQL_DB_PORT:
  JWT_ACCESS_TOKEN_SECRET:
  JWT_REFRESH_TOKEN_SECRET:

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: nirmalazurecr.azurecr.io/users
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: users-config
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
